spring.application.name=api
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mi_app_db}
spring.datasource.username=${DB_USER:mi_app_user}
spring.datasource.password=${DB_PASSWORD:mi_app_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}

resend.api.key=${RESEND_API_KEY:algo}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CAS_URL:http://cas:8080/realms/mathtexpedia}